version: "3.8"
services:
    web:
        image: cnfdnc/bgapp-web
        deploy:
            replicas: 3
        ports:
            - 8080:80
        volumes:
            - "${PROJECT_ROOT}:/var/www/html:ro"
            - ./default:/etc/nginx/sites-enabled/default:ro
        networks:
            - app-network
    
    db:
        image: cnfdnc/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:

